version: '3.8'

services:
    db:
        image: mysql:8.2.0
        restart: always
        mem_limit: 1000m
        #THIS MUST BE ADDED AT SERVICE LEVEL
        shm_size: 1gb
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=local
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - '3306:3306'
        volumes:
            - db:/var/lib/postgresql/data
    redis:
        container_name: laravel-redis
        image: redis:6.2-alpine
        mem_limit: 500m
        ports:
            - '127.0.0.1:6379:6379'
        restart: always

volumes:
    db:
        driver: local
    opa-data: {}
